global:
  scrape_interval: 15s # Pull má»—i 15s
  evaluation_interval: 15s # Eval rules

scrape_configs:
  - job_name: "ml-inference"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["ml-service:8000"]
